### ISSUE TITLE
Notebooks TODO

### ISSUE THREAD

**Issue by grchristensen** [grchristensen/avpd#6]
1. Automated threshold discovery
2. MICUSP data extraction
3. Function to split text into sentences and annotate each sentence with the distance from the profile.
4. Refactor architecture so that not every class has to split sentences in order to work.

**Comment by NoahWong123** [comment]
1. Add APIs needed for UI
    a) Student request to get classes they are in
    b) Update "List students" so that is displays first and last name //right now it only has id number for students
    c) Message between students and instructor if we want in app messaging
2. I have some problems with loading a file into Post submit and I do not know what is wrong so it would be great if someone could look at it.

**Comment by grchristensen** [comment]
TODO lists are being split into separate issues for each TODO.
