### ISSUE TITLE
Frontend TODO

### ISSUE THREAD

**Issue by grchristensen** [grchristensen/avpd#7]
1. Add APIs needed for UI
    a) Student request to get classes they are in
    b) Update "List students" so that is displays first and last name //right now it only has id number for students
    c) Message between students and instructor if we want in app messaging

**Comment by grchristensen** [comment]
I'll look into 1. tomorrow

**Comment by NoahWong123** [comment]
2. more APIs needed for UI
    a) View Submissions and List Submissions API do not display name on both instructor and student

**Comment by grchristensen** [comment]
For c) we can consider in app messaging once we have our first release done. Other items have been split into their own issues.
